#!/usr/bin/env python27
# -*- coding: UTF-8 -*-
# github:micky-git /Hello-python
# A script try to send a plain email titled with datetime
from email.header import Header
from email.mime.text import MIMEText
import smtplib, datetime
#gb2312
title = 'Test'
text = 'hello'
sender = '188001069@qq.com'
receiver = ['188001069@qq.com','1903952396@qq.com']
SMTPserver = 'smtp.qq.com'
SMTPport = 587
user = '' #usually same with sender
password = '' #password for logining
msg = MIMEText(text,'plain')
msg['subject'] = Header(title + '(' + str(datetime.date.today()) + ')','utf-8')
server = smtplib.SMTP(SMTPserver,SMTPport)
server.starttls()
server.login(user,password)
for receiver1 in receiver:
    server.sendmail(sender,receiver1, msg.as_string())
server.quit()
